name: Personal Site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

 jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
 steps:
      - uses: actions/checkout@v2
      # Frontend
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps
        run: npm install
      - name: Build project
        run: npm run build
      
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_KEY }}"
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"